raw_data_base: "/Users/lauraporta/Source/github/neuroinformatics-unit/photon-mosaic/tests/data/"
processed_data_base: "/Users/lauraporta/Source/github/neuroinformatics-unit/photon-mosaic/tests/data/"
suite2p_ops:
  fs: 7.5
  nplanes: 2
  tau: 0.8
  nonrigid: true
  diameter: 10
slurm:
  use_slurm: true
  partition: "cpu"
  mem_mb: 16000
  cpu_per_task: 1
  tasks: 1
  nodes: 1
