rule setup:
    input:
        "/nfs/winstor/margrie/SimonWeiler/RawData/Invivo_imaging/3photon_rotation/shared/",
        "/ceph/margrie/laura/cimaut/",
    params:
        folder_read_pattern="2*",
        file_read_pattern=["rotation_00001.tif", "*.bin"],
    output: "datasets.csv"
    run:
        "calcium_imaging_automation/core/rules/setup.py"
        
# import pandas as pd

# paths = pd.read_csv("datasets.csv")

# rule all:
#     input:
#         expand("preprocess_output_{index}.txt", index=paths["index"])

# rule preprocess:
#     input:
#         lambda wildcards: paths.loc[int(wildcards.index), "read_dataset_path"],
#         lambda wildcards: paths.loc[int(wildcards.index), "write_dataset_path"],
#     output:
#         "preprocess_output_{index}.txt"
#     params:
#         index=lambda wildcards: wildcards.index
#     resources:
#         partition="fast",
#         mem_mb=16000,
#         cpu_per_task=1,
#         tasks=1,
#         nodes=1,
#     script:
#         "calcium_imaging_automation/core/rules/preprocess.py"
